version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /backend/node_modules
      - ./backend:/backend
    ports:
      - 3001:3001
    container_name: backend_container

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - 3000:3000
    image: frontend:frontend
    container_name: frontend_container

